name: "Sanity check (YAML only)"

on:
  workflow_dispatch: {}
  push:
    branches: ["main"]
    paths:
      - ".github/workflows/auto-pr-mock-shipment.yml"

jobs:
  ok:
    runs-on: ubuntu-latest
    steps:
      - run: echo "YAML OK"
